// <auto-generated />
using System;
using Manifest.Scheduler.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Manifest.Scheduler.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Manifest.Scheduler.Domain.GalacticSenate.Entities.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Parties", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Manifest.Scheduler.Domain.GalacticSenate.Entities.PartyRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.ToTable("PartyRoles");
                });

            modelBuilder.Entity("Manifest.Scheduler.Domain.GalacticSenate.Entities.Organization", b =>
                {
                    b.HasBaseType("Manifest.Scheduler.Domain.GalacticSenate.Entities.Party");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("Manifest.Scheduler.Domain.GalacticSenate.Entities.Person", b =>
                {
                    b.HasBaseType("Manifest.Scheduler.Domain.GalacticSenate.Entities.Party");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("Manifest.Scheduler.Domain.GalacticSenate.Entities.PartyRole", b =>
                {
                    b.HasOne("Manifest.Scheduler.Domain.GalacticSenate.Entities.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Manifest.Scheduler.Domain.GalacticSenate.Entities.Organization", b =>
                {
                    b.HasOne("Manifest.Scheduler.Domain.GalacticSenate.Entities.Party", null)
                        .WithOne()
                        .HasForeignKey("Manifest.Scheduler.Domain.GalacticSenate.Entities.Organization", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Manifest.Scheduler.Domain.GalacticSenate.Entities.Person", b =>
                {
                    b.HasOne("Manifest.Scheduler.Domain.GalacticSenate.Entities.Party", null)
                        .WithOne()
                        .HasForeignKey("Manifest.Scheduler.Domain.GalacticSenate.Entities.Person", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
